name: reviewdog
on: [push]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@master
        with:
          checkstyle_config: google_checks.xml
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
